name: grocery_core
description: Core functionalities for grocery shop applications including cart management, product handling, and business logic.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
